version: '3.8'

services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend_app
    ports:
      - "3000:3000"
    networks:
      - github_network # On connecte ton app à ce réseau
    environment:
      - PORT=3000
      - DB_HOST=mariadb # IMPORTANT : Dans le même réseau Docker, le Host devient le nom du service GitHub !
      - DB_PORT=3306
      - DB_NAME=mabase
      - DB_USER=root
      - DB_PASSWORD=root

networks:
  github_network:
    name: ${DOCKER_NETWORK} # Récupère dynamiquement le réseau de GitHub Actions !
    external: true