version: '3.8'

services:
  # 1. Ta base de données MariaDB
  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_NAME}
    # Nous ne mappons pas le port à l'extérieur car l'API y accède en interne
    networks:
      - app_network

  # 2. Ton Backend Node.js (depuis GHCR)
  backend:
    # --- CHANGE ICI TON PSEUDO ET TON DEPOT ---
    image: ghcr.io/ton-pseudo/ton-depot/backend:latest
    build: ./backend
    environment:
      DB_HOST: database # Le nom du service MariaDB
      DB_PORT: 3306
      MARIADB_NAME: ${MARIADB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3000:3000 # On expose l'API sur le port 3000 de ton PC
    depends_on:
      - database
    networks:
      - app_network

  # 3. Ton Frontend Nginx (depuis GHCR)
  frontend:
    # --- CHANGE ICI TON PSEUDO ET TON DEPOT ---
    image: ghcr.io/thsykas/automated-devops-workflow/frontend:latest
    build: ./frontend
    ports:
      - 8080:80 # On expose le front sur le port 8080 de ton PC
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

# http://localhost:8080/